name: Deploy to S3
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and dependencies
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci

    - name: Build the website
      run: npm run build

    - name: Deploy to S3
      uses: aws-actions/s3-sync-action@v0.5.0
      with:
        source-dir: build
        bucket: workshop.bolecodex.com
        bucket-region: us-east-1
        delete: true

    - name: Invalidate CloudFront Cache
      uses: chetan/invalidate-cloudfront-action@v1
      with:
        distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        paths: '/*'
